In [6]:
import gsd.hoomd
import numpy as np
import pyknotid
import pyknotid.spacecurves
from pyknotid.spacecurves import Link as link
from pyknotid.invariants import alexander
np.random.seed(42)

# Function to read GSD file and extract data
def read_gsd_file(file_path):
    trajectory = gsd.hoomd.open(file_path, 'r')
    frames = [frame for frame in trajectory]  # Extract all frames
    return frames

# Path to your GSD file
file_path = 'chainlength5.gsd'

# Read the GSD file
frames = read_gsd_file(file_path)

# Process the first frame (or choose a specific frame)
frame = frames[0]

# Assuming the frame contains particles' positions in 3D space
points = frame.particles.position

# Since your original code expects data in a specific shape, we'll need to reshape the points
# Assuming mol_size is the same as the number of particles per molecule in your GSD file
mol_size = 5  # Update this value based on your specific data
data = points.reshape([-1, mol_size, 3])

print(data, data.shape)

stride = 1

data = data[:, ::stride, :]

print(data.shape)

# Assuming the simulation box side length is known
box_size = 53.7321  # This magic number is the simulation box side length
links = link.from_periodic_lines(data, shape=[box_size] * 3)
links.smooth(periodic=False)
a = links.linking_number(include_closures=True)

links.plot()

print('LINKING NUMBER: ', a)


[[[-5.7598815 -0.7125374  0.7150457]
  [-5.735672  -0.6887396  1.3721919]
  [-5.7123227 -0.6656797  2.0061877]
  [-5.6889734 -0.6426197  2.6401832]
  [-5.6644    -0.6183461  3.307425 ]]

 [[ 0.3621584 -2.946702   2.4521103]
  [ 0.2294349 -2.9252682  1.8079686]
  [ 0.1013484 -2.9046824  1.1865207]
  [-0.0267382 -2.8840969  0.5650728]
  [-0.1615432 -2.8624358 -0.0889632]]

 [[-2.7520845 -0.8286596  0.3107123]
  [-2.303666  -1.2189904  0.0286546]
  [-1.8711153 -1.5956384 -0.2434915]
  [-1.4385645 -1.9722863 -0.5156375]
  [-0.9833341 -2.3686883 -0.8020557]]

 [[ 3.957873   3.9074707  2.8849607]
  [ 4.3294587  4.1639647  2.406287 ]
  [ 4.6878777  4.411481   1.944444 ]
  [ 5.0462966  4.6589975  1.482601 ]
  [ 5.4235077  4.9194956  0.9965381]]

 [[ 2.941293  -3.514688  -5.5123587]
  [ 2.8245366 -3.0896828 -5.0237565]
  [ 2.7119696 -2.6795905 -4.5523963]
  [ 2.5994024 -2.2694983 -4.081036 ]
  [ 2.4809358 -1.8378985 -3.5849595]]

 [[-3.9352767  0.3334713  3.442922 ]
  [-4.349989   0.839553   3.

RuntimeError: Could not import backend "jupyter_rfb":
The jupyter_rfb backend relies on a the jupyter_rfb library: ``pip install jupyter_rfb``