In [6]:
import numpy as np
import pyknotid
import pyknotid.spacecurves
from pyknotid.spacecurves import Link as link
from pyknotid.invariants import alexander
np.random.seed(42)

# default is 120 from the "detanglement-start.gsd"
# which has 120-mers
def get_data(fpath, mol_size=5):
    raw = np.genfromtxt(fpath, skip_header=2)
    molecule_lines = raw.reshape([-1, mol_size, 3])
    return molecule_lines

data_file = 'chainlength5.XYZ'

data = get_data(data_file)

print(data, data.shape)


stride = 1

data = data[:,::stride,:]

print(data.shape)

# this magic number is the simulation box side length
links = link.from_periodic_lines(data, shape=[53.7321]*3)
links.smooth(periodic=False)
a=links.linking_number(include_closures=True)

links.plot()

print('LINKING NUMBER: ', a)

[[[-5.7598815  -0.71253741  0.71504569]
  [-5.735672   -0.6887396   1.37219191]
  [-5.71232271 -0.66567969  2.00618768]
  [-5.68897343 -0.64261973  2.64018321]
  [-5.6644001  -0.6183461   3.30742502]]

 [[ 0.36215839 -2.946702    2.45211029]
  [ 0.22943491 -2.92526817  1.80796862]
  [ 0.1013484  -2.9046824   1.1865207 ]
  [-0.0267382  -2.88409686  0.56507277]
  [-0.16154321 -2.86243582 -0.0889632 ]]

 [[-2.75208449 -0.82865959  0.31071231]
  [-2.30366611 -1.21899045  0.0286546 ]
  [-1.87111533 -1.59563839 -0.2434915 ]
  [-1.43856454 -1.97228634 -0.51563752]
  [-0.98333412 -2.36868834 -0.80205572]]

 [[ 3.95787311  3.9074707   2.88496065]
  [ 4.32945871  4.16396475  2.40628695]
  [ 4.68787766  4.4114809   1.94444394]
  [ 5.0462966   4.65899754  1.48260105]
  [ 5.42350769  4.91949558  0.9965381 ]]

 [[ 2.941293   -3.51468801 -5.51235867]
  [ 2.82453656 -3.08968282 -5.0237565 ]
  [ 2.71196961 -2.67959046 -4.5523963 ]
  [ 2.59940243 -2.26949835 -4.08103609]
  [ 2.48093581 -1.83789849 -3.58

RuntimeError: Could not import backend "jupyter_rfb":
The jupyter_rfb backend relies on a the jupyter_rfb library: ``pip install jupyter_rfb``